### ISSUE TITLE
Cookies are not valid

### ISSUE THREAD

**Issue by Elinkami** [Julius-Ulee/King-Genshin-StarRail-Stats#5]
Getting this error "genshin.errors.InvalidCookies: [-100] Cookies are not valid."

My cookie token, ltoken, ltuid & account id have now been updated to v2  
I had to use this method to get my cookies https://github.com/Joshua-Noakes1/mei-cards?tab=readme-ov-file#2-getting-your-hoyolab-cookies

I have the cookie secret formatted like this {"ltuid": " 00000000", "ltoken": "v2_000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "account_id": "00000000", "cookie_token": "v2_000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"}

**Comment by 0zunu** [comment]
Since Hoyolab uses v2 cookies, you can simply change the JSON format to something like this:

```json
{"ltuid_v2": "...", "ltoken_v2": "...", "cookie_token_v2": "...", "account_id_v2": "...", "ltmid_v2": "..."}
```

**Comment by Elinkami** [comment]
Thanks I don't get the cookie error and it gets my Genshin & HSR stats now. Auto redemption of codes doesn't seem to work though

**Comment by 0zunu** [comment]
Redeem code is fixed
